### ISSUE TITLE
mHeaderControl not allowing capture of favicons

### ISSUE THREAD

**Issue by bit-blit** [maheee/mHeaderControl#6]
With mHeaderConrol enabled and all preferences set to default (or using a fake referrer set to on), if you bookmark a  page it will not capture the favicon. If I disable mHC, I can bookmark and the favicon is captured as well. **Bug?**

Best Regards

**Comment by Atavic** [comment]
More like a feature, maybe hiding/spoofing the referrer breaks the favicon request.

**Comment by bit-blit** [comment]
I believe this to be a bug. Here is why:

[1] With mHC enabled and **no preferences have been set** (everything is set to off), It will not capture the favicon when bookmarking a page.

[2] If I go into the Firefox add-ons manager and disable mHC, I can bookmark as normal and the favicon is captured.

[3] I tested this using RefControl (a legacy add-on) and it works as expected - **even when I spoof the referer**

[4] As stated above, this only happens if I have mHC enabled (even with no features on). As soon as I **disable** it (in add-ons manager), the proper behaviour returns.

I am very grateful for this add-on, but I truly think this is a bug - I cannot keep disabling mHC in add-ons manager just to bookmark a site, and then go back and re-enable it everytime.

Please look into this. Thank you for a great add-on!!! I am so glad I found mHC because it is a webextension and will work with future versions of Firefox.

Thanks! bit-blit

**Comment by maheee** [comment]
Yup, don't worry, it is a bug. When all settings are set to default, it shouldn't do anything at all.

To determine which set of rules to apply for a request, I retrieve the URL from the tab the request is in and load the settings for this URL. I didn't consider though that some requests are not in the scope of a tab. Favicon request is one of those (maybe others too, don't know yet). Right now, it then throws an error (NPE) and this prevents the favicon stuff in FF from working.

Fix is on the way.

But, if you use this plugin for security reasons, consider that currently only global rules will be applied to out-of-tab-requests like the favicon request.

And yes, it's a webextension because I wrote it because all the addons I need for web development started to have the "legacy" flag and that freaked me out 😃

**Comment by bit-blit** [comment]
**Many many thanks for the fix (1.0.4)!!!!!!!**

bit-blit
